ReNatureEnabled: false
JunkieEnabled: false
RPGItemEnabled: false
UnnamedPortalPluginEnabled: false
RentablesEnabled: false
AmbienceEnabled: false
InventoryBackupEnabled: false
DeathAndRebirthEnabled: false
KarmaEnabled: false
ChaintrainEnabled: false
MyLittleFarmEnabled: false
ActivityWatcherEnabled: false
UsePermissions: true
MaxWorldEditBlocksForCreation: 200